{% set package_name = "whatrecord" %}
{% set import_name = "whatrecord" %}
{% set version = load_file_regex(load_file=os.path.join(import_name, "_version.py"), regex_pattern=".*version = '(\S+)'").group(1) %}

package:
  name: {{ package_name }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  - python >=3.9
  - pip
  - setuptools_scm
  run:
  - python >=3.9
  - aiohttp
  - apischema
  - epicsmacrolib
  - graphviz
  - jinja2
  - lark
  - python-graphviz <0.18

test:
  requires:
    - blark
    - codecov
    - flake8
    - happi
    - pytest
    - pytest-asyncio
    - pytest-cov
    - python-ldap
    - pytmc
  imports:
    - whatrecord

about:
  home: https://github.com/pcdshub/whatrecord
  license: SLAC Open License
  summary: EPICS IOC record search and meta information tool
